In [ ]:

import numpy as np
'''
NumPy (short for Numerical Python) is one of the most popular Python libraries for scientific computing and numerical operations. It provides a fast and efficient way to work with large collections of numbers and multidimensional arrays.
NumPy arrays:
Store data in contiguous memory (each process is assigned a single continuous block of memory )
Use optimized C-based implementations internally
Require less memory
Perform mathematical operations much faster than standard Python lists
'''

In [ ]:
import pandas as pd
'''Pandas is a powerful Python library used for data manipulation, analysis, and processing. It helps you work with structured data such as tables, spreadsheets, CSV files, and databases.
Series - A one-dimensional labeled array that can hold any data type (integers, strings, floats, etc.). It is similar to a column in a spreadsheet or a database table.
DataFrame - A two-dimensional labeled data structure that can hold multiple Series (columns) of different data types. It is similar to a table in a relational database or an Excel spreadsheet.'''

In [3]:
s1 = pd.Series(["nalin","jermone","shek"])
s2 = pd.Series([11,21,31])
print(s1)
print(s2)

0      nalin
1    jermone
2       shek
dtype: str
0    11
1    21
2    31
dtype: int64

In [ ]:
m1 = pd.Series([1,2,3,4,5],["one","two","three","four","five"]) # values and the keys
m1["one"] = 10
print(m1)

one      10
two       2
three     3
four      4
five      5
dtype: int64

In [ ]:
m1["six"] = 6 #add new key and value
print(m1)

one      10
two       2
three     3
four      4
five      5
six       6
dtype: int64

In [9]:
new  =  pd.Series([7,8],["seven","eight"])
m1 = pd.concat([m1,new]) # add new series to the existing series
print(m1)

one      10
two       2
three     3
four      4
five      5
six       6
seven     7
eight     8
dtype: int64

loc → Selects data using labels (row/column names).

iloc → Selects data using integer positions (indexes).

In [ ]:
n1 = pd.Series([1,2,3,4,5],index=["one","two","three","four","five"])

#df.iloc[row_position, column_position]
print(n1.iloc[0]) # access the first element of the series
print(n1.iloc[[0, 2]])

print(n1.loc["one":"four"]) # access the element with the key "one"

1
one      1
two      2
three    3
four     4
dtype: int64

In [13]:
print(n1.loc[n1>2]) # access the elements greater than 2

three    3
four     4
five     5
dtype: int64

In [15]:
n1.loc["six"] = 6 # add new key and value
print(n1)

one      1
two      2
three    3
four     4
five     5
6        6
six      6
dtype: int64

In [16]:
n1 = n1 + 10
print(n1) # add 10 to all the values in the series

one      11
two      12
three    13
four     14
five     15
6        16
six      16
dtype: int64

In [18]:
n1["six"] += 10 # add 10 to the value of the key "six"
print(n1)

one      11
two      12
three    13
four     14
five     15
6        16
six      36
dtype: int64

In [19]:
n1 = n1.drop("six") # remove the key and value
print(n1)

one      11
two      12
three    13
four     14
five     15
6        16
dtype: int64

In [20]:
print("maximum",n1.max()) # maximum value in the series
print("minimum",n1.min()) # minimum value in the series
print("sum",n1.sum()) # sum of all values in the series
print("mean",n1.mean()) # mean of all values in the series
print("median",n1.median()) # median of all values in the series
print("standard deviation",n1.std()) # standard deviation of all values in the series
print(n1.sort_index()) # sort the series by index
print(n1.sort_values()) # sort the series by values

maximum 16
minimum 11
sum 81
mean 13.5
median 13.5
standard deviation 1.8708286933869707
6        16
five     15
four     14
one      11
three    13
two      12
dtype: int64
one      11
two      12
three    13
four     14
five     15
6        16
dtype: int64

In [24]:
print(n1.values) # get the values of the series
print(n1.index) # get the index of the series
print(n1.shape) # get the shape of the series
print(n1.size) # get the size of the series
print(n1.ndim) # get the number of dimensions of the series
print(n1.head()) # get the first 5 elements of the series
print(n1.tail()) # get the last 5 elements of the series

[11 12 13 14 15 16]
Index(['one', 'two', 'three', 'four', 'five', '6'], dtype='str')
(6,)
6
1
one      11
two      12
three    13
four     14
five     15
dtype: int64
two      12
three    13
four     14
five     15
6        16
dtype: int64

In [25]:
print(n1.describe()) # get the summary statistics of the series
print(n1.unique()) # get the unique values of the series
print(n1.nunique()) # get the number of unique values of the series

count     6.000000
mean     13.500000
std       1.870829
min      11.000000
25%      12.250000
50%      13.500000
75%      14.750000
max      16.000000
dtype: float64
[11 12 13 14 15 16]
6

In [27]:
s = pd.Series([1,2,3,4,5], dtype="int32") # specify the data type of the series
s1 = pd.Series([1,2,3,4,5], dtype="float32") # specify the data type of the series
s2 = pd.Series([1,2,3,4,5], dtype="string") # specify the data type of the series
print(s)
print(s1)
print(s2)

0    1
1    2
2    3
3    4
4    5
dtype: int32
0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float32
0    1
1    2
2    3
3    4
4    5
dtype: string

In [31]:
students = pd.Series(
    [85, np.nan, 78, np.nan, 95],
    index=["John", "Sara", "David", "Anu", "Ram"]
)

print(students.notna())
print("--------------")
print(students)
print("--------------")
print(students.isna())
print("--------------")
print(students.isna().sum())
print("--------------")
print(students.dropna())

John      True
Sara     False
David     True
Anu      False
Ram       True
dtype: bool
--------------
John     85.0
Sara      NaN
David    78.0
Anu       NaN
Ram      95.0
dtype: float64
--------------
John     False
Sara      True
David    False
Anu       True
Ram      False
dtype: bool
--------------
2
--------------
John     85.0
David    78.0
Ram      95.0
dtype: float64

In [33]:
print(students.bfill()) # fill the missing values with the next valid value
print("--------------")
print(students.ffill()) # fill the missing values with the previous valid value

John     85.0
Sara     78.0
David    78.0
Anu      95.0
Ram      95.0
dtype: float64
--------------
John     85.0
Sara     85.0
David    78.0
Anu      78.0
Ram      95.0
dtype: float64

In [34]:
dates = pd.Series([
    "2022-05-10",
    "2023-08-15",
    "2024-12-20"
])

dates = pd.to_datetime(dates)
dates = pd.to_datetime(dates, format="%d/%m/%Y")
print(dates)

0   2022-05-10
1   2023-08-15
2   2024-12-20
dtype: datetime64[us]

dataframe - A two-dimensional labeled data structure that can hold multiple Series (columns) of different data types. It is similar to a table in a relational database or an Excel spreadsheet.

In [35]:
df = pd.DataFrame({
    "Name": ["John", "Sara", "David", "Anu", "Ram"],
    "Age": [25, 30, 22, 28, 35]
})
print(df)

    Name  Age
0   John   25
1   Sara   30
2  David   22
3    Anu   28
4    Ram   35

In [36]:
data = [
    ["John", 25],
    ["Sara", 30],
    ["David", 22],
    ["Anu", 28],
    ["Ram", 35]
]
df = pd.DataFrame(data, columns=["Name", "Age"])
print(df)

    Name  Age
0   John   25
1   Sara   30
2  David   22
3    Anu   28
4    Ram   35

In [37]:
names =pd.Series(["John", "Sara", "David", "Anu", "Ram"])
ages = pd.Series([25, 30, 22, 28, 35])
df = pd.DataFrame({"Name": names, "Age": ages})
print(df)

    Name  Age
0   John   25
1   Sara   30
2  David   22
3    Anu   28
4    Ram   35

In [ ]:
students =pd.DataFrame(["John", "Sara", "David", "Anu", "Ram"])
print(students.index)

RangeIndex(start=1, stop=6, step=1)

In [ ]:
students =pd.DataFrame(["John", "Sara", "David", "Anu", "Ram"])
students.index = range(1, 10,2) # Create an index with values 1, 3, 5, 7, 9
print(students.index)

RangeIndex(start=1, stop=10, step=2)

In [ ]:
marks = pd.DataFrame({
    "Math": ["John", "Sara", "David", "Anu", "Ram"],
    "Science": [85, 90, 78, 92, 95]
}, index=["John", "Sara", "David", "Anu", "Ram"])
print(marks.T) # transpose the dataframe

         John  Sara  David  Anu  Ram
Math     John  Sara  David  Anu  Ram
Science    85    90     78   92   95

In [45]:
df = pd.read_csv("telecom_churn.csv") # read a csv file into a dataframe
print(df.head()) # print the first 5 rows of the dataframe

   customer_id telecom_partner gender  age              state     city  \
0            1    Reliance Jio      F   25          Karnataka  Kolkata
1            2    Reliance Jio      F   55            Mizoram   Mumbai
2            3        Vodafone      F   57  Arunachal Pradesh    Delhi
3            4            BSNL      M   46         Tamil Nadu  Kolkata
4            5            BSNL      F   26            Tripura    Delhi

   pincode date_of_registration  num_dependents  estimated_salary  calls_made  \
0   755597           2020-01-01               4            124962          44
1   125926           2020-01-01               2            130556          62
2   423976           2020-01-01               0            148828          49
3   522841           2020-01-01               1             38722          80
4   740247           2020-01-01               2             55098          78

   sms_sent  data_used  churn
0        45       -361      0
1        39       5973      0
2        24        193      1
3        25       9377      1
4        15       1393      0

In [ ]:

print(df.shape) #rows and columns

print("----------------------------")
print(df.size) #total number of elements in the dataframe

print("----------------------------")
print(df.ndim) #number of dimensions

print("----------------------------")
print(df.columns) #column names

print("----------------------------")
print(df.index) #row labels

print("----------------------------")
print(df.axes[1]) #Returns both row and column axes.

(243553, 14)
----------------------------
3409742
----------------------------
2
----------------------------
Index(['customer_id', 'telecom_partner', 'gender', 'age', 'state', 'city',
       'pincode', 'date_of_registration', 'num_dependents', 'estimated_salary',
       'calls_made', 'sms_sent', 'data_used', 'churn'],
      dtype='str')
----------------------------
RangeIndex(start=0, stop=243553, step=1)
RangeIndex(start=0, stop=243553, step=1)
----------------------------
Index(['customer_id', 'telecom_partner', 'gender', 'age', 'state', 'city',
       'pincode', 'date_of_registration', 'num_dependents', 'estimated_salary',
       'calls_made', 'sms_sent', 'data_used', 'churn'],
      dtype='str')

In [50]:
print(df[df["churn"] == 1]) # filter the dataframe based on a condition

        customer_id telecom_partner gender  age              state       city  \
2                 3        Vodafone      F   57  Arunachal Pradesh      Delhi
3                 4            BSNL      M   46         Tamil Nadu    Kolkata
7                 8            BSNL      M   46  Arunachal Pradesh    Kolkata
10               11          Airtel      M   44        Uttarakhand    Chennai
16               17        Vodafone      M   61   Himachal Pradesh  Hyderabad
...             ...             ...    ...  ...                ...        ...
243523       243524    Reliance Jio      F   38            Gujarat      Delhi
243527       243528            BSNL      F   50      Uttar Pradesh     Mumbai
243529       243530    Reliance Jio      M   45             Punjab    Kolkata
243533       243534    Reliance Jio      F   22        West Bengal    Kolkata
243535       243536            BSNL      M   32     Andhra Pradesh      Delhi

        pincode date_of_registration  num_dependents  estimated_salary  \
2        423976           2020-01-01               0            148828
3        522841           2020-01-01               1             38722
7        866786           2020-01-01               4            104541
10       776250           2020-01-01               0            133288
16       734068           2020-01-01               2             59723
...         ...                  ...             ...               ...
243523   112512           2023-05-03               0             69163
243527   613558           2023-05-03               3            126994
243529   190431           2023-05-03               2            110127
243533   732518           2023-05-03               2            123399
243535   439538           2023-05-03               1            104748

        calls_made  sms_sent  data_used  churn
2               49        24        193      1
3               80        25       9377      1
7               87        40       2245      1
10               7         7       1275      1
16              16        42       8157      1
...            ...       ...        ...    ...
243523          86        10       7323      1
243527          39         2       3186      1
243529          58        24       2852      1
243533          69         9        448      1
243535          62        15       4743      1

[48827 rows x 14 columns]

In [51]:
print(df.at[2, "gender"]) # access a specific value in the dataframe using the index and column name

F

In [58]:
data =pd.DataFrame ({
    "ID": [1, 2, 3, 4, 5],
    "Name": ["John", "Sara", "David", "Anu", "Ram"],
    "Age": [25, 30, 22, 28, 35],
    "Gender": ["Male", "Female", "Male", "Female", "Male"]
})

In [59]:
data["phone_number"] = ["1234567890", "0987654321", "5678901234", "4321098765", "6789012345"] # add a new column to the dataframe
print(data)

   ID   Name  Age  Gender phone_number
0   1   John   25    Male   1234567890
1   2   Sara   30  Female   0987654321
2   3  David   22    Male   5678901234
3   4    Anu   28  Female   4321098765
4   5    Ram   35    Male   6789012345

In [60]:
data.drop(["Gender"], axis=1, inplace=True) # remove a column from the dataframe    
print(data)

   ID   Name  Age phone_number
0   1   John   25   1234567890
1   2   Sara   30   0987654321
2   3  David   22   5678901234
3   4    Anu   28   4321098765
4   5    Ram   35   6789012345

In [61]:
data.rename(columns={"ID": "customer_id"}, inplace=True) # rename columns in the dataframe
print(data)

   customer_id   Name  Age phone_number
0            1   John   25   1234567890
1            2   Sara   30   0987654321
2            3  David   22   5678901234
3            4    Anu   28   4321098765
4            5    Ram   35   6789012345

In [ ]:
#pivot_table() function is used to create a pivot table in pandas. A pivot table is a data summarization tool that is used to summarize and aggregate data in a tabular format. It allows you to group data by one or more columns and perform calculations on the grouped data.
#cross_tab() function is used to create a cross tabulation in pandas. A cross tabulation is a table that shows the relationship between two or more categorical variables. It allows you to see how the values of one variable are distributed across the values of another variable.
#melt() function is used to reshape a dataframe from wide format to long format. It allows you to convert columns into rows, making it easier to analyze and visualize the data.
#stack() function is used to reshape a dataframe from wide format to long format. It allows you to convert columns into rows, making it easier to analyze and visualize the data.
#unstack() function is used to reshape a dataframe from long format to wide format. It allows you to convert rows into columns, making it easier to analyze and visualize the data.
#cross_tab() function is used to create a cross tabulation in pandas. A cross tabulation is a table that shows the relationship between two or more categorical variables. It allows you to see how the values of one variable are distributed across the values of another variable.

In [1]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['A', 'A', 'B', 'B'],
    'Product': ['Laptop', 'Mobile', 'Laptop', 'Mobile'],
    'Sales': [50000, 20000, 60000, 25000]
})

print(df)

  Name Product  Sales
0    A  Laptop  50000
1    A  Mobile  20000
2    B  Laptop  60000
3    B  Mobile  25000

In [2]:
#pivot table groups data and performs aggregation (sum, mean, count, etc.).
pd.pivot_table(
    df,
    values='Sales',
    index='Name',
    columns='Product',
    aggfunc='sum'
)

Product  Laptop  Mobile
Name
A         50000   20000
B         60000   25000

In [3]:
#crosstab() Creates a frequency table showing relationships between categorical variables.

df = pd.DataFrame({
    'Gender': ['M','F','M','F','M'],
    'Result': ['Pass','Pass','Fail','Pass','Fail']
})

pd.crosstab(df['Gender'], df['Result'])

Result  Fail  Pass
Gender
F          0     2
M          2     1

In [4]:
# melt() Converts wide format → long format.
df = pd.DataFrame({
    'Name': ['A', 'B'],
    'Math': [90, 80],
    'Science': [85, 75]
})

print(df)

  Name  Math  Science
0    A    90       85
1    B    80       75

In [6]:
pd.melt(
    df
)

  variable value
0     Name     A
1     Name     B
2     Math    90
3     Math    80
4  Science    85
5  Science    75

In [7]:
#stack() - Converts columns into rows by creating a hierarchical index.
df = pd.DataFrame({
    'Math': [90, 80],
    'Science': [85, 75]
}, index=['A', 'B'])

print(df)

   Math  Science
A    90       85
B    80       75

In [8]:
df.stack()

A  Math       90
   Science    85
B  Math       80
   Science    75
dtype: int64

In [9]:
#unstack() - reverses the stack operation, converting rows back into columns. It allows you to reshape a dataframe from long format to wide format, making it easier to analyze and visualize the data.
s = df.stack()

print(s)

A  Math       90
   Science    85
B  Math       80
   Science    75
dtype: int64

In [10]:
s.unstack()

   Math  Science
A    90       85
B    80       75